name: fftechsol

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_EWARENET }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EWARENET }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://fftechsol.com --exclude '.git/*' --exclude '.github/*'